version: '3.9'

services:

  fm-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      fm-db :
        condition: service_started
    restart: on-failure
  fm-db:
    image: mariadb
    restart: always
    environment:
      MARIADB_PASSWORD: secret_password
      MARIADB_ROOT_PASSWORD: secret_password
    ports:
      - "3307:3306"
    volumes:
      - fm_data:/var/lib/mysql/data/

networks:
  default:
volumes:
  fm_data:

